/*
    This file was autogenerated by ButtonParsePro
*/

#ifndef _SOURCE_BUTTONS_H
#define _SOURCE_BUTTONS_H

#include <message.h>

/* PIO defines */
#define BUTTON_PAIR_CONNECT 0x800
#define BUTTON_POWER 0x800000
#define CHARGER 0x400000

/* Raw PIO defines */

/* Button actions */
typedef enum
{
    ENTER,
    RELEASE,
    HELD,
    HELD_RELEASE,
    DOUBLE
} ActionType;

/* Button task messages to client */
typedef enum
{        
    BUTTON_MSG_ENTER_PAIRING_MODE = 1000,
    BUTTON_MSG_RESET_PAIRED_DEVICE_LIST,
    BUTTON_MSG_ON_OFF_HELD,
    CHARGER_CONNECTED,
    BUTTON_MSG_CONNECT,
    BUTTON_MSG_ON_OFF_RELEASE,
    CHARGER_DISCONNECTED,
    PIO_RAW                         /* always the last value */
} PioMessage;

typedef uint32 pio_bits_t;

/*
 * PIO_RAW message type
 */

typedef struct _pio_raw_t
{
    pio_bits_t pio;
} PIO_RAW_T;

typedef struct
{
    pio_bits_t      bits;
    pio_bits_t      mask;
    ActionType      action;  
    uint16          timeout;
    uint16          repeat;       /* only used for HELD and ENTER actions */
    PioMessage      message;
} PioActionMessage;

typedef struct _pio_stored_states
{
    /* The PIO bits, as last read or indicated */
    pio_bits_t                  pio_bits;           
    /* PIO deep sleep wake up state PS Key setting */
    uint16                      pskey_wakeup;
    /* The PIO bits, whose release message is to be
       suppressed */
    pio_bits_t                  pio_release_disabled;
    /* PAM state stored for timers */
    const PioActionMessage      *held_release;
    const PioActionMessage      *repeat;
    const PioActionMessage      *double_tap; 
} PioStoredStates;

typedef struct _pio_state
{
TaskData        task;
    Task            client;
    PioStoredStates stored;
} PioState;

/*
 * Function prototypes
 */

void pioInit(PioState *state, Task client);

#endif
